### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hroncok** [mricon/grokmirror#17]
I'm trying to find out if grokmirror works with Python 3 or not, however, there is no information in `setup.py` metadata, readme etc. Does it? Thanks

**Comment by mricon** [comment]
Not at this time, but this is very high on my list.

**Comment by hroncok** [comment]
Awesome! Shall we use this issue to track this?

I recommend this particular guide: [The Conservative Python 3 Porting Guide](https://portingguide.readthedocs.io/). It helped me port one project recently with ease. Also, if I may offer any help, don't hesitate to ask. I'm not saying I'm willing the port grokmirror to Python 3 myself, yet I have ported several projects before and can answer some questions and give hints, if you are interested.

One hint: grokmirror uses subprocess. Stdout, stderr and stdin are handled as bytes on Ptyhon 3 unless you specify `encoding` (Python 3.6+ only argument) or set `universal_newlines` to `True` (that works on all currently supported Python versions and 2.6 as well).

**Comment by QuLogic** [comment]
Are there any tests? This seems like the easiest conversion I've ever attempted, but I'm worried it's just easier than it looks.
