### ISSUE TITLE
Tag release 1.1.1

### ISSUE THREAD

**Issue by Tharre** [mricon/grokmirror#25]
As the title says, please tag 1.1.1 so it can be properly packaged downstream.

Thanks.

**Comment by Tharre** [comment]
Ah, I thought it was the other way around since PyPy lists the github repo as "source".

Thanks.

**Comment by mricon** [comment]
Fixed now, thanks for pointing that out. I also pushed 1.1.1 to pypi, which I totally forgot to do as well.
